test:
  message: CIAO MONDO
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    hostname: configuration
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://discovery:8762/eureka
    serviceUrl:
      defaultZone: http://discovery:8762/eureka
